/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ShipmentManagerRole;

import Business.EcoSystem;
import Business.Enterprise.RetailerEnterprise;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.Organization;
import Business.Organization.RetailerOrderOrganization;
import Business.Organization.ShipmentOrganization;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gourav
 */
public class RetailerOrderWorkAreaJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
private UserAccount account;
private RetailerOrderOrganization organization;
private RetailerEnterprise enterprise;
private EcoSystem business;
Order order=new Order();

    /**
     * Creates new form RetailerOrderWorkAreaJPanel
     */
    public RetailerOrderWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, RetailerOrderOrganization organization,RetailerEnterprise enterprise, EcoSystem business) {
     
     initComponents();
    this.account = account;
        this.userProcessContainer = userProcessContainer;
        this.business=business;
        this.organization=organization;
        this.enterprise=enterprise;
        
        populateOrderTable();
        
    }


    
    
      OrderWorkRequest orderWorkR = null;
    
      private void populateOrderTable() {
        DefaultTableModel model = (DefaultTableModel)retailerOrderTable.getModel();
        model.setRowCount(0);

        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof OrderWorkRequest) {
                orderWorkR = (OrderWorkRequest)wr;

                Object row[] = new Object[4];
                row[0] = orderWorkR;
                //row[1] = orderWorkR.getProductID();
                row[1] = orderWorkR.getStatus();
                row[2] = orderWorkR.getRequestDate();
                row[3] = orderWorkR.getResolveDate();
                

                model.addRow(row);

            }
        }





    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        retailerOrderTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("RETAILER ORDER DEPARTMENT WORK AREA");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 11, -1, -1));

        jButton1.setText("To Shippment>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 201, -1, -1));

        retailerOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Status", "Requested Date", "Solve Date"
            }
        ));
        jScrollPane1.setViewportView(retailerOrderTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 547, 132));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        int selectedRow =retailerOrderTable.getSelectedRow();
        
        
       if (selectedRow < 0) {
            return;
       }
            OrderWorkRequest request=(OrderWorkRequest)retailerOrderTable.getValueAt(selectedRow,0);
             order =new Order();
            for(OrderItem oi:request.getOrderItemList()){
                
              Product p=oi.getProduct();
              int quant=oi.getQuantity();
              double totalPrice=oi.getProduct().getTargetP();
              
              OrderItem o1=order.addOrderItem();
              o1.setProduct(p);
              o1.setQuantity(quant);
              o1.setSellingP(totalPrice);
            }
            
            request.setOrder(order);
            request.setStatus("Shipment Under Process");
            
            ShipmentOrganization rso=null;
            for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList()){
                if(org instanceof ShipmentOrganization){
                    
                    rso=(ShipmentOrganization)org;
                    rso.getWorkQueue().addWorkRequest(request);
                
            }
            
            }
        
            populateOrderTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable retailerOrderTable;
    // End of variables declaration//GEN-END:variables
}
