/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.Customer;

import Business.EcoSystem;
import Business.Enterprise.AmazonEnterprise;
import Business.Enterprise.Enterprise;
import Business.Invoice.Invoice;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Order.Payment;
import Business.Organization.AmazonFinanceOrganization;
import Business.Organization.AmazonOrderOrganization;
import Business.Organization.Organization;
import Business.Organization.RetailerOrderOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AmazonFinanceWorkRequest;
import Business.WorkQueue.OrderWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gourav
 */
public class MyInvoiceJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount ua;
    private AmazonEnterprise AmEnt;
    private EcoSystem ecoSys;
    private Invoice invoice;
    private Order order;

    /**
     * Creates new form MyInvoiceJPanel
     */
    public MyInvoiceJPanel(JPanel userProcessContainer, UserAccount ua, AmazonEnterprise AmEnt, EcoSystem ecosys, Invoice invoice, Order order) {
        initComponents();
        this.AmEnt = AmEnt;
        this.ua = ua;
        this.ecoSys = ecosys;
        this.invoice = invoice;
        this.order = order;
        this.userProcessContainer = userProcessContainer;

        initForm();
        populateCombo();
    }

    private void initForm() {

        amountJLabel.setText(String.valueOf(order.getTotal()));
    }

    private void populateCombo() {
        CardTypeCombo.removeAllItems();
        CardTypeCombo.addItem("Debit");
        CardTypeCombo.addItem("Credit");
        monthComboBox.removeAllItems();
        YearComboBox.removeAllItems();

        monthComboBox.addItem("Jan");
        monthComboBox.addItem("Feb");
        monthComboBox.addItem("Mar");
        monthComboBox.addItem("Apr");
        monthComboBox.addItem("May");
        YearComboBox.addItem("13");
        YearComboBox.addItem("14");
        YearComboBox.addItem("15");
        YearComboBox.addItem("16");
        YearComboBox.addItem("17");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreditCardNumber = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        YearComboBox = new javax.swing.JComboBox();
        backJButton = new javax.swing.JButton();
        ClickToPayJButton = new javax.swing.JButton();
        cardSecurityNumber = new javax.swing.JTextField();
        CardTypeCombo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        monthComboBox = new javax.swing.JComboBox();
        billingAmountJTextFiled = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        amountJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("Enter Credit Card Number");

        YearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        ClickToPayJButton.setText("Click to Pay");
        ClickToPayJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickToPayJButtonActionPerformed(evt);
            }
        });

        CardTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CardTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardTypeComboActionPerformed(evt);
            }
        });

        jLabel9.setText("Select Card Type");

        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Enter Name(on Card)");

        jLabel4.setText("Card Security Number");

        jLabel7.setText("Enter Billing Amount");

        jLabel5.setText("Expiry Date");

        jLabel10.setText("Amount To Pay:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("MAKE PAYMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(53, 53, 53)
                                .addComponent(amountJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(35, 35, 35)
                                    .addComponent(billingAmountJTextFiled))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(28, 28, 28)
                                    .addComponent(nameJTextField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(6, 6, 6)
                                    .addComponent(CreditCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(25, 25, 25)
                                    .addComponent(cardSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(backJButton))
                                    .addGap(59, 59, 59)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ClickToPayJButton)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(48, 48, 48)
                                    .addComponent(CardTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(370, 370, 370))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CardTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(billingAmountJTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(CreditCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cardSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton)
                            .addComponent(ClickToPayJButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void ClickToPayJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickToPayJButtonActionPerformed
        // TODO add your handling code here:

        int cardnumber, code;
        float amt;
        try {
            cardnumber = Integer.parseInt(CreditCardNumber.getText());
            code = Integer.parseInt(cardSecurityNumber.getText());
            amt = Float.parseFloat(billingAmountJTextFiled.getText());
        }
        catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(null, "Please Enter a Valid value", "Invalid Entry", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (amt == Float.parseFloat(amountJLabel.getText())) {

            Payment pay = invoice.addPayment();
            
            pay.setPaymentType((String) CardTypeCombo.getSelectedItem());
            pay.setCardNumber(String.valueOf(cardnumber));
            pay.setCardName(nameJTextField.getText());
            pay.setSecurityCode(code);
            pay.setAmountReceived(amt);

            System.out.println(pay.getAmountReceived());
            invoice.setInvoicestatus("paid");
            

            JOptionPane.showMessageDialog(null, "Thank you for the Payment");


           // java.util.Date date = new java.util.Date();
            //Timestamp ts = new Timestamp(date.getTime());
      
            
           // pay.setTs(ts);
            Date date=new Date();
        


        AmazonFinanceWorkRequest aaa = new AmazonFinanceWorkRequest();

        aaa.setInvoice(invoice);
        aaa.setRequestDate(date);
        
        AmazonFinanceOrganization forg = null;

        for (Organization org : AmEnt.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof AmazonFinanceOrganization) {


                forg = (AmazonFinanceOrganization) org;
                forg.getWorkQueue().addWorkRequest(aaa);
            }
        }







        ArrayList<Enterprise> orderEnterpriseList = new ArrayList<>();

        for (OrderItem oi : order.getOrderItemList()) {
            if (!(orderEnterpriseList.contains(oi.getProduct().getEnterprise()))) {
                orderEnterpriseList.add(oi.getProduct().getEnterprise());
            }
        }
        for (Enterprise e : orderEnterpriseList) {
            //System.out.println(" size: "+orderEnterpriseList.size());
            OrderWorkRequest orderWorkReq = new OrderWorkRequest();

            for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                RetailerOrderOrganization ro = null;
               
                if (org instanceof RetailerOrderOrganization) {
                   
                    ro = (RetailerOrderOrganization)org;
                    for (OrderItem orderItem : order.getOrderItemList()) {

                        
                        if (orderItem.getProduct().getEnterprise().equals(e)) {
                            ro.getWorkQueue().addWorkRequest(orderWorkReq);
                            
                            orderWorkReq.setProductID(orderItem.getProduct().getProductID());
                            orderWorkReq.setEnterprise(e);
                           // orderWorkReq.setRequestDate(date);
                            orderWorkReq.setStatus("Under Process");
                            orderWorkReq.setCustomer(order.getCustomer().getName());

                            orderWorkReq.setProductName(orderItem.getProduct().getName());

                            orderWorkReq.getOrderItemList().add(orderItem);

                            
                        }
                    }
                }

            }
    

        }
        }
        else{
                 JOptionPane.showMessageDialog(null, " Please Enter Correct Amount");
    }
        
    for (Organization oo : AmEnt.getOrganizationDirectory().getOrganizationList()){
                            
                                if (oo instanceof AmazonOrderOrganization) {
            AmazonOrderOrganization aoo = (AmazonOrderOrganization) oo;

            aoo.getMasterordercatlog().addOrder(order);
        }

    }
    //JOptionPane.showMessageDialog(null, "Payment Successfully Done..!! Thanks..");
            
            
            
    }//GEN-LAST:event_ClickToPayJButtonActionPerformed
    private void CardTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardTypeComboActionPerformed
        // TODO add your handling code here:
        nameJTextField.setEnabled(true);
        cardSecurityNumber.setEnabled(true);
        monthComboBox.setEnabled(true);

        YearComboBox.setEnabled(true);



    }//GEN-LAST:event_CardTypeComboActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CardTypeCombo;
    private javax.swing.JButton ClickToPayJButton;
    private javax.swing.JTextField CreditCardNumber;
    private javax.swing.JComboBox YearComboBox;
    private javax.swing.JLabel amountJLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField billingAmountJTextFiled;
    private javax.swing.JTextField cardSecurityNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox monthComboBox;
    private javax.swing.JTextField nameJTextField;
    // End of variables declaration//GEN-END:variables
}
