/*
 * SystemAdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package UserInterface.SystemAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  gourav
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    /** Creates new form SystemAdminWorkAreaJPanel */
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageEnterpriseAdminJButton = new javax.swing.JButton();
        manageEnterpriseJButton = new javax.swing.JButton();
        manageNetworkJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        manageAmazonJButton = new javax.swing.JButton();
        manageAmazonAdminJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SYSTEM ADMIN-WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 21, -1, -1));

        manageEnterpriseAdminJButton.setText("Manage Retailer Enterprise Admin");
        manageEnterpriseAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAdminJButtonActionPerformed(evt);
            }
        });
        add(manageEnterpriseAdminJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        manageEnterpriseJButton.setText("Manage Retailer Enterprise");
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });
        add(manageEnterpriseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 179, 195, -1));

        manageNetworkJButton.setText("Manage Network");
        manageNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButtonActionPerformed(evt);
            }
        });
        add(manageNetworkJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 68, 195, -1));

        jButton1.setText("Manage Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 109, 195, -1));

        manageAmazonJButton.setText("Manage Amazon Enterprise");
        manageAmazonJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAmazonJButtonActionPerformed(evt);
            }
        });
        add(manageAmazonJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 293, 195, -1));

        manageAmazonAdminJButton.setText("Manage Amazon Admin");
        manageAmazonAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAmazonAdminJButtonActionPerformed(evt);
            }
        });
        add(manageAmazonAdminJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 334, 195, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageEnterpriseAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminJButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseAdminJButtonActionPerformed

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed

        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer, system);
        userProcessContainer.add("manageEnterpriseJPanel", manageEnterpriseJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    private void manageNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButtonActionPerformed

        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(userProcessContainer, system);
        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         ManageRequestJPanel manageRequestJPanel = new ManageRequestJPanel(userProcessContainer, system);
        userProcessContainer.add("manageNetworkJPanel", manageRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manageAmazonJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAmazonJButtonActionPerformed
        // TODO add your handling code here:
        
         ManageAmazonJPanel manageAmazonJPanel = new ManageAmazonJPanel(userProcessContainer, system);
        userProcessContainer.add("manageAmazonJPanel", manageAmazonJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_manageAmazonJButtonActionPerformed

    private void manageAmazonAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAmazonAdminJButtonActionPerformed
        // TODO add your handling code here:
        
        ManageAmazonAdminJPanel manageAmazonAdminJPanel = new ManageAmazonAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("manageAmazonJPanel", manageAmazonAdminJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_manageAmazonAdminJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAmazonAdminJButton;
    private javax.swing.JButton manageAmazonJButton;
    private javax.swing.JButton manageEnterpriseAdminJButton;
    private javax.swing.JButton manageEnterpriseJButton;
    private javax.swing.JButton manageNetworkJButton;
    // End of variables declaration//GEN-END:variables
    
}
