/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseAdministrativeRole;


import Business.Enterprise.RetailerEnterprise;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Product.Product;
import Business.Product.ProductDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gourav
 */
public class CreateNewProductJPanel extends javax.swing.JPanel {
private JPanel UserProcessContainer;
    private ProductDirectory pd;
    private RetailerEnterprise eee;
    /**
     * Creates new form CreateNewProductJPanel
     */
    public CreateNewProductJPanel(JPanel userProcessContainer,RetailerEnterprise enterp) {
        initComponents();
         this.UserProcessContainer=userProcessContainer;
         this.eee=enterp;
        //this.pd=productDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        nameField1 = new javax.swing.JTextField();
        backButton6 = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        targerPriceJTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productQuantityJTextField = new javax.swing.JTextField();
        localTaxJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setText("Product Name:");

        nameField1.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N

        backButton6.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        backButton6.setText("<< Back");
        backButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton6ActionPerformed(evt);
            }
        });

        createButton.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        createButton.setText("Add Product");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Product Selling Price");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("ADD NEW PRODUCT");

        jLabel3.setText("Product Quantity");

        jLabel4.setText("Local Tax");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(backButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel5)
                                        .addGap(62, 62, 62)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(productQuantityJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                        .addComponent(targerPriceJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createButton)
                                    .addComponent(localTaxJTextField))))))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(targerPriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(productQuantityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localTaxJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(createButton)
                .addGap(30, 30, 30)
                .addComponent(backButton6)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton6ActionPerformed

        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_backButton6ActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
       
       
     if(eee!=null){
         double aa=0,dd=0; String bb=null; int cc=0;
           
         if(nameField1.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Please enter the product name");
             return;  
         }
         
         
         try{
             bb=nameField1.getText();
       aa=Double.parseDouble(targerPriceJTextField.getText());
       cc=Integer.parseInt(productQuantityJTextField.getText());
       dd=Double.parseDouble(localTaxJTextField.getText());
       
                          
            }
            
        catch(Exception ee)
        {
             JOptionPane.showMessageDialog(null, "Please enter the valid value");
             return;
        }
         for(Organization o: eee.getOrganizationDirectory().getOrganizationList()){
         InventoryOrganization io = null;
         if(o instanceof InventoryOrganization){
         io = (InventoryOrganization) o;
         
          Product product = io.getProductdirectory().addProduct();
         
         product.setTargetP(aa);
          product.setName(bb);
         product.setQuantity(cc);
         product.setTax(dd);
         product.setEnterprise(eee);
     
         }
         }
     
    
    
        JOptionPane.showMessageDialog(null, "Product information Saved");
    } 
    else{
                   JOptionPane.showMessageDialog(null, "something went wrong");
     }
        nameField1.setText(" ");
       // retailPriceJTextField.setText("");
        targerPriceJTextField.setText(" ");
        productQuantityJTextField.setText("");
        localTaxJTextField.setText(" ");
    }//GEN-LAST:event_createButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton6;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField localTaxJTextField;
    private javax.swing.JTextField nameField1;
    private javax.swing.JTextField productQuantityJTextField;
    private javax.swing.JTextField targerPriceJTextField;
    // End of variables declaration//GEN-END:variables
}
