/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FinanceManagerRole;

import Business.EcoSystem;
import Business.Enterprise.AmazonEnterprise;
import Business.Organization.AmazonFinanceOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author gourav
 */
public class AmazonFirstWorkArea extends javax.swing.JPanel {
 private JPanel userProcessContainer;
    private AmazonFinanceOrganization org;
    private AmazonEnterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    /**
     * Creates new form AmazonFirstWorkArea
     */
    public AmazonFirstWorkArea(JPanel userProcessContainer, UserAccount account,AmazonFinanceOrganization organization, AmazonEnterprise enterprise,EcoSystem ecos) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.org = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.ecosystem=ecos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        orderRequestJButton = new javax.swing.JButton();
        divisionPayment = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("AMAZON FINANCE DEPARTMENT WORK AREA");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        orderRequestJButton.setText("Order Request Management");
        orderRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderRequestJButtonActionPerformed(evt);
            }
        });
        add(orderRequestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 116, -1, -1));

        divisionPayment.setText("Division Of Payments");
        divisionPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionPaymentActionPerformed(evt);
            }
        });
        add(divisionPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 54, 171, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void orderRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderRequestJButtonActionPerformed
        // TODO add your handling code here:
        
         AmazonFinanceManagerWorkAreaJPanel afmwajp = new  AmazonFinanceManagerWorkAreaJPanel(userProcessContainer,userAccount,org,enterprise,ecosystem);
        userProcessContainer.add(" AmazonFinanceManagerWorkAreaJPanel", afmwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_orderRequestJButtonActionPerformed

    private void divisionPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionPaymentActionPerformed
        // TODO add your handling code here:
        
        AmazonPaymentDivisonJPanel apdjp = new AmazonPaymentDivisonJPanel(userProcessContainer,userAccount,org,enterprise,ecosystem);
        userProcessContainer.add("AmazonPaymentDivisonJPanel", apdjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_divisionPaymentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton divisionPayment;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton orderRequestJButton;
    // End of variables declaration//GEN-END:variables
}
