/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.Supplier;

import Business.EcoSystem;
import Business.WorkQueue.NewAccountWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gourav
 */
public class RequestAccountJPanel extends javax.swing.JPanel {
 private JPanel userProcessContainer;
    private EcoSystem system;
    private String nn;
    /**
     * Creates new form RequestAccountJPanel
     */
    public RequestAccountJPanel(JPanel upc,EcoSystem system,String nn) {
        initComponents();
          this.userProcessContainer=upc;
        this.system=system;
        this.nn=nn;
        
        usernameJTextFiled.setText(nn);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        requestJButton = new javax.swing.JButton();
        supplierNameJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        trackingIdJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameJTextFiled = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordJTextField = new javax.swing.JTextField();
        requestJButton1 = new javax.swing.JButton();
        requestJButton2 = new javax.swing.JButton();
        viewStatusjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 244, -1, -1));

        requestJButton.setText("Request");
        requestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestJButtonActionPerformed(evt);
            }
        });
        add(requestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 210, -1, -1));
        add(supplierNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 64, 131, -1));

        jLabel1.setText("Supplier Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 67, -1, -1));

        trackingIdJTextField.setEnabled(false);
        trackingIdJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackingIdJTextFieldActionPerformed(evt);
            }
        });
        add(trackingIdJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 172, 131, -1));

        jLabel2.setText("Tracking ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 175, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("REGISTER ACCOUNT WORK AREA");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 11, -1, -1));

        jLabel3.setText("UserName");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 105, -1, -1));
        add(usernameJTextFiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 102, 131, -1));

        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 137, -1, -1));
        add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 134, 131, -1));

        requestJButton1.setText("Request");
        requestJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestJButton1ActionPerformed(evt);
            }
        });
        add(requestJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 210, -1, -1));

        requestJButton2.setText("Request");
        requestJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestJButton2ActionPerformed(evt);
            }
        });
        add(requestJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 210, -1, -1));

        viewStatusjButton.setText("View Status");
        viewStatusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStatusjButtonActionPerformed(evt);
            }
        });
        add(viewStatusjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void requestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestJButtonActionPerformed
        // TODO add your handling code here:
         String name = supplierNameJTextField.getText();
        
         String pass=passwordJTextField.getText();
        
         
         NewAccountWorkRequest request = new NewAccountWorkRequest();
                
         trackingIdJTextField.setText(String.valueOf(request.getId()));
        request.setMessage(name);
       
         String ID = trackingIdJTextField.getText();

        /// request.setTempID(Integer.parseInt(ID));
             if(name.equals("")||name.equals(" ")){
            JOptionPane.showMessageDialog(null, "Please Enter the username");
            return; 
         }
        else if(pass.equals("")||pass.equals(" "))
         {
            JOptionPane.showMessageDialog(null, "Please Enter the password");
            return;
         }
        else{
       
        request.setStatus("Sent");
        request.setUsername(usernameJTextFiled.getText());
        request.setPassword(passwordJTextField.getText());
        
        system.getWorkQueue().getWorkRequestList().add(request);
        }
    }//GEN-LAST:event_requestJButtonActionPerformed

    private void trackingIdJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackingIdJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trackingIdJTextFieldActionPerformed

    private void requestJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestJButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestJButton1ActionPerformed

    private void requestJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestJButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestJButton2ActionPerformed

    private void viewStatusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStatusjButtonActionPerformed
        // TODO add your handling code here:
         ViewStatusJPanel vsjp = new ViewStatusJPanel(userProcessContainer,system,nn);
        userProcessContainer.add("ViewStatusJPanel", vsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewStatusjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField passwordJTextField;
    private javax.swing.JButton requestJButton;
    private javax.swing.JButton requestJButton1;
    private javax.swing.JButton requestJButton2;
    private javax.swing.JTextField supplierNameJTextField;
    private javax.swing.JTextField trackingIdJTextField;
    private javax.swing.JTextField usernameJTextFiled;
    private javax.swing.JButton viewStatusjButton;
    // End of variables declaration//GEN-END:variables
}
